# Generated by Django 4.2.19 on 2025-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('student', 'Student'), ('admin', 'Admin')], max_length=10)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
