# Generated by Django 4.2.19 on 2025-03-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_user_delete_customuser_alter_report_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
