# Generated by Django 4.2.19 on 2025-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_delete_announcement_delete_menu_remove_report_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Worker', 'Worker'), ('Student', 'Student')], max_length=20),
        ),
    ]
